export const FETCH_BLOG_POST_REQUEST = 'FETCH_BLOG_POST_REQUEST'
export const FETCH_BLOG_POST_SUCCESS = 'FETCH_BLOG_POST_SUCCESS'
export const FETCH_BLOG_POST_FAILURE = 'FETCH_BLOG_POST_FAILURE'

export const FETCH_SINGLE_BLOG_REQUEST = 'FETCH_SINGLE_BLOG_REQUEST'
export const FETCH_SINGLE_BLOG_SUCCESS = 'FETCH_SINGLE_BLOG_SUCCESS'
export const FETCH_SINGLE_BLOG_FAILURE = 'FETCH_SINGLE_BLOG_FAILURE'